export const WORKER_SERVICE = 'WORKER_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const DB_CONNECTION = 'DB_CONNECTION';
export const TASK_REPOSITORY = 'TASK_REPOSITORY';
