export enum Policy {
  WORKSPACE_MANAGEMENT,
  ROLE_MANAGEMENT,
  USER_MANAGEMENT,
  PROJECT_MANAGEMENT,
  SPRINT_MANAGEMENT,
  ISSUE_MANAGEMENT,
  BACKLOG_ACCESS,
  ROADMAP_ACCESS,
  REPORT_ACCESS,
}
