FROM node:alpine

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src

# add `/usr/src/node_modules/.bin` to $PATH
ENV PATH /usr/src/node_modules/.bin:$PATH

# install and cache app dependencies
ADD package.json /usr/src/package.json
RUN yarn install
# RUN yarn install pm2 -g

# start app
CMD ["yarn", "run", "start:dev"]
# CMD [ "pm2-runtime", "npm", "run", "start:prod" ]