export const DB_CONNECTION = 'DATABASE_CONNECTION';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CACHE_SERVICE = 'CACHE_SERVICE';
export const CACHE_TTL = 60 * 60;
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
